! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Auxiliary Routines File
! 
! Generated by KPP-2.2 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : KPP_Util.f90
! Time                 : Tue Nov  9 23:09:28 2010
! Working directory    : /home/amir/carleton/amir/work/kpp/cb5_cl_ae5_aq
! Equation file        : cb5.kpp
! Output root filename : cb5
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE KPP_Util

  USE KPP_Parameters
  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Shuffle_user2kpp - function to copy concentrations from USER to KPP
!   Arguments :
!      V_USER    - Concentration of variable species in USER's order
!      V         - Concentrations of variable species (local)
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_user2kpp ( V_USER, V )

! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)
! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)

  V(62) = V_USER(1)
  V(63) = V_USER(2)
  V(64) = V_USER(3)
  V(60) = V_USER(4)
  V(66) = V_USER(5)
  V(19) = V_USER(6)
  V(72) = V_USER(7)
  V(68) = V_USER(8)
  V(23) = V_USER(9)
  V(46) = V_USER(10)
  V(26) = V_USER(11)
  V(32) = V_USER(12)
  V(25) = V_USER(13)
  V(67) = V_USER(14)
  V(53) = V_USER(15)
  V(59) = V_USER(16)
  V(40) = V_USER(17)
  V(61) = V_USER(18)
  V(58) = V_USER(19)
  V(57) = V_USER(20)
  V(54) = V_USER(21)
  V(44) = V_USER(22)
  V(69) = V_USER(23)
  V(43) = V_USER(24)
  V(34) = V_USER(25)
  V(37) = V_USER(26)
  V(27) = V_USER(27)
  V(70) = V_USER(28)
  V(20) = V_USER(29)
  V(28) = V_USER(30)
  V(29) = V_USER(31)
  V(71) = V_USER(32)
  V(30) = V_USER(33)
  V(47) = V_USER(34)
  V(52) = V_USER(35)
  V(49) = V_USER(36)
  V(51) = V_USER(37)
  V(22) = V_USER(38)
  V(48) = V_USER(39)
  V(31) = V_USER(40)
  V(7) = V_USER(41)
  V(45) = V_USER(42)
  V(38) = V_USER(43)
  V(39) = V_USER(44)
  V(24) = V_USER(45)
  V(10) = V_USER(46)
  V(55) = V_USER(47)
  V(56) = V_USER(48)
  V(1) = V_USER(49)
  V(50) = V_USER(50)
  V(2) = V_USER(51)
  V(18) = V_USER(52)
  V(3) = V_USER(53)
  V(4) = V_USER(54)
  V(35) = V_USER(55)
  V(33) = V_USER(56)
  V(17) = V_USER(57)
  V(65) = V_USER(58)
  V(21) = V_USER(59)
  V(41) = V_USER(60)
  V(42) = V_USER(61)
  V(36) = V_USER(62)
  V(5) = V_USER(63)
  V(6) = V_USER(64)
  V(8) = V_USER(65)
  V(9) = V_USER(66)
  V(14) = V_USER(67)
  V(13) = V_USER(68)
  V(11) = V_USER(69)
  V(12) = V_USER(70)
  V(16) = V_USER(71)
  V(15) = V_USER(72)
      
END SUBROUTINE Shuffle_user2kpp

! End of Shuffle_user2kpp function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Shuffle_kpp2user - function to restore concentrations from KPP to USER
!   Arguments :
!      V         - Concentrations of variable species (local)
!      V_USER    - Concentration of variable species in USER's order
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_kpp2user ( V, V_USER )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)

  V_USER(1) = V(62)
  V_USER(2) = V(63)
  V_USER(3) = V(64)
  V_USER(4) = V(60)
  V_USER(5) = V(66)
  V_USER(6) = V(19)
  V_USER(7) = V(72)
  V_USER(8) = V(68)
  V_USER(9) = V(23)
  V_USER(10) = V(46)
  V_USER(11) = V(26)
  V_USER(12) = V(32)
  V_USER(13) = V(25)
  V_USER(14) = V(67)
  V_USER(15) = V(53)
  V_USER(16) = V(59)
  V_USER(17) = V(40)
  V_USER(18) = V(61)
  V_USER(19) = V(58)
  V_USER(20) = V(57)
  V_USER(21) = V(54)
  V_USER(22) = V(44)
  V_USER(23) = V(69)
  V_USER(24) = V(43)
  V_USER(25) = V(34)
  V_USER(26) = V(37)
  V_USER(27) = V(27)
  V_USER(28) = V(70)
  V_USER(29) = V(20)
  V_USER(30) = V(28)
  V_USER(31) = V(29)
  V_USER(32) = V(71)
  V_USER(33) = V(30)
  V_USER(34) = V(47)
  V_USER(35) = V(52)
  V_USER(36) = V(49)
  V_USER(37) = V(51)
  V_USER(38) = V(22)
  V_USER(39) = V(48)
  V_USER(40) = V(31)
  V_USER(41) = V(7)
  V_USER(42) = V(45)
  V_USER(43) = V(38)
  V_USER(44) = V(39)
  V_USER(45) = V(24)
  V_USER(46) = V(10)
  V_USER(47) = V(55)
  V_USER(48) = V(56)
  V_USER(49) = V(1)
  V_USER(50) = V(50)
  V_USER(51) = V(2)
  V_USER(52) = V(18)
  V_USER(53) = V(3)
  V_USER(54) = V(4)
  V_USER(55) = V(35)
  V_USER(56) = V(33)
  V_USER(57) = V(17)
  V_USER(58) = V(65)
  V_USER(59) = V(21)
  V_USER(60) = V(41)
  V_USER(61) = V(42)
  V_USER(62) = V(36)
  V_USER(63) = V(5)
  V_USER(64) = V(6)
  V_USER(65) = V(8)
  V_USER(66) = V(9)
  V_USER(67) = V(14)
  V_USER(68) = V(13)
  V_USER(69) = V(11)
  V_USER(70) = V(12)
  V_USER(71) = V(16)
  V_USER(72) = V(15)
      
END SUBROUTINE Shuffle_kpp2user

! End of Shuffle_kpp2user function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

END MODULE KPP_Util

