! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : KPP_Parameters.f90
! Time                 : Tue Nov  9 23:09:28 2010
! Working directory    : /home/amir/carleton/amir/work/kpp/cb5_cl_ae5_aq
! Equation file        : cb5.kpp
! Output root filename : cb5
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE KPP_Parameters

  USE KPP_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 73 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 72 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 61 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 1 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: KNREACT = 187 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 73 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 655 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 734 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 73 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 666 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_ISOPRXN = 1 
  INTEGER, PARAMETER :: ind_TRPRXN = 2 
  INTEGER, PARAMETER :: ind_SULF = 3 
  INTEGER, PARAMETER :: ind_SULRXN = 4 
  INTEGER, PARAMETER :: ind_TOLNRXN = 5 
  INTEGER, PARAMETER :: ind_TOLHRXN = 6 
  INTEGER, PARAMETER :: ind_TOLRO2 = 7 
  INTEGER, PARAMETER :: ind_XYLNRXN = 8 
  INTEGER, PARAMETER :: ind_XYLHRXN = 9 
  INTEGER, PARAMETER :: ind_XYLRO2 = 10 
  INTEGER, PARAMETER :: ind_BNZNRXN = 11 
  INTEGER, PARAMETER :: ind_BNZHRXN = 12 
  INTEGER, PARAMETER :: ind_BENZRO2 = 13 
  INTEGER, PARAMETER :: ind_BENZENE = 14 
  INTEGER, PARAMETER :: ind_SESQRXN = 15 
  INTEGER, PARAMETER :: ind_SESQ = 16 
  INTEGER, PARAMETER :: ind_CL2 = 17 
  INTEGER, PARAMETER :: ind_SO2 = 18 
  INTEGER, PARAMETER :: ind_O1D = 19 
  INTEGER, PARAMETER :: ind_PAN = 20 
  INTEGER, PARAMETER :: ind_HOCL = 21 
  INTEGER, PARAMETER :: ind_TOL = 22 
  INTEGER, PARAMETER :: ind_N2O5 = 23 
  INTEGER, PARAMETER :: ind_XYL = 24 
  INTEGER, PARAMETER :: ind_H2O2 = 25 
  INTEGER, PARAMETER :: ind_HONO = 26 
  INTEGER, PARAMETER :: ind_FACD = 27 
  INTEGER, PARAMETER :: ind_PACD = 28 
  INTEGER, PARAMETER :: ind_AACD = 29 
  INTEGER, PARAMETER :: ind_PANX = 30 
  INTEGER, PARAMETER :: ind_TO2 = 31 
  INTEGER, PARAMETER :: ind_PNA = 32 
  INTEGER, PARAMETER :: ind_ETHA = 33 
  INTEGER, PARAMETER :: ind_MEOH = 34 
  INTEGER, PARAMETER :: ind_ETOH = 35 
  INTEGER, PARAMETER :: ind_HCL = 36 
  INTEGER, PARAMETER :: ind_HCO3 = 37 
  INTEGER, PARAMETER :: ind_CRO = 38 
  INTEGER, PARAMETER :: ind_MGLY = 39 
  INTEGER, PARAMETER :: ind_ROOH = 40 
  INTEGER, PARAMETER :: ind_CLO = 41 
  INTEGER, PARAMETER :: ind_FMCL = 42 
  INTEGER, PARAMETER :: ind_MEPX = 43 
  INTEGER, PARAMETER :: ind_CO = 44 
  INTEGER, PARAMETER :: ind_OPEN = 45 
  INTEGER, PARAMETER :: ind_HNO3 = 46 
  INTEGER, PARAMETER :: ind_ROR = 47 
  INTEGER, PARAMETER :: ind_CRES = 48 
  INTEGER, PARAMETER :: ind_ETH = 49 
  INTEGER, PARAMETER :: ind_TERP = 50 
  INTEGER, PARAMETER :: ind_IOLE = 51 
  INTEGER, PARAMETER :: ind_OLE = 52 
  INTEGER, PARAMETER :: ind_XO2N = 53 
  INTEGER, PARAMETER :: ind_PAR = 54 
  INTEGER, PARAMETER :: ind_ISOP = 55 
  INTEGER, PARAMETER :: ind_ISPD = 56 
  INTEGER, PARAMETER :: ind_ALDX = 57 
  INTEGER, PARAMETER :: ind_ALD2 = 58 
  INTEGER, PARAMETER :: ind_NTR = 59 
  INTEGER, PARAMETER :: ind_O3 = 60 
  INTEGER, PARAMETER :: ind_FORM = 61 
  INTEGER, PARAMETER :: ind_NO2 = 62 
  INTEGER, PARAMETER :: ind_NO = 63 
  INTEGER, PARAMETER :: ind_O = 64 
  INTEGER, PARAMETER :: ind_CL = 65 
  INTEGER, PARAMETER :: ind_NO3 = 66 
  INTEGER, PARAMETER :: ind_XO2 = 67 
  INTEGER, PARAMETER :: ind_HO2 = 68 
  INTEGER, PARAMETER :: ind_MEO2 = 69 
  INTEGER, PARAMETER :: ind_C2O3 = 70 
  INTEGER, PARAMETER :: ind_CXO3 = 71 
  INTEGER, PARAMETER :: ind_OH = 72 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_DUMMY = 73 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_DUMMY = 1 

END MODULE KPP_Parameters

